//
//  User.swift
//  2048
//
//  Created by lhvan on 6/5/17.
//  Copyright © 2017 lhvan. All rights reserved.
//

import Foundation
var arrUserAnonymous = [
    ["Anonymous Alligator","Cá sấu ẩn danh","alligator_lg"],
    ["Anonymous Anteater","Thú ăn kiến ẩn danh","anteater_lg"],
    ["Anonymous Armadillo","Con Tatu ẩn danh","armadillo_lg"],
    ["Anonymous Aurochs","Bò rừng ẩn danh","auroch_lg"],
    ["Anonymous Axolotl","Ấu trùng Axolot ẩn danh","axolotl_lg"],
    ["Anonymous Badger","Con lửng ẩn danh","badger_lg"],
    ["Anonymous Bat","Dơi ẩn danh","bat_lg"],
    ["Anonymous Beaver","Hải ly ẩn danh","beaver_lg"],
    ["Anonymous Buffalo","Trâu ẩn danh","buffalo_lg"],
    ["Anonymous Camel","Lạc đà ẩn danh","camel_lg"],
    ["Anonymous Capybara","Chuột lang nước ẩn danh","capybara_lg"],
    ["Anonymous Chameleon","Tắc kè hoa ẩn danh","chameleon_lg"],
    ["Anonymous Cheetah","Báo đốm ẩn danh","cheetah_lg"],
    ["Anonymous Chinchilla","Sóc sinsin ẩn danh","chinchilla_lg"],
    ["Anonymous Chipmunk","Sóc chuột ẩn danh","chipmunk_lg"],
    ["Anonymous Cormorant","Chim cốc ẩn danh","cormorant_lg"],
    ["Anonymous Coyote","Chó sói đồng cỏ ẩn danh","coyote_lg"],
    ["Anonymous Crow","Quạ ẩn danh","crow_lg"],
    ["Anonymous Dingo","Chó Dingo ẩn danh","dingo_lg"],
    ["Anonymous Dinosaur","Khủng long ẩn danh","dinosaur_lg"],
    ["Anonymous Dolphin","Cá heo ẩn danh","dolphin_lg"],
    ["Anonymous Duck","Vịt ẩn danh","duck_lg"],
    ["Anonymous Elephant","Voi ẩn danh","elephant_lg"],
    ["Anonymous Ferret","Chồn sương ẩn danh","ferret_lg"],
    ["Anonymous Fox","Cáo ẩn danh","fox_lg"],
    ["Anonymous Frog","Ếch ẩn danh","frog_lg"],
    ["Anonymous Giraffe","Hươu cao cổ ẩn danh","giraffe_lg"],
    ["Anonymous Gopher","Chuột nang ẩn danh","gopher_lg"],
    ["Anonymous Grizzly","Gấu xám ẩn danh","grizzly_lg"],
    ["Anonymous Hedgehog","Nhím Âu ẩn danh","hedgehog_lg"],
    ["Anonymous Hippo","Hà mã ẩn danh","hippo_lg"],
    ["Anonymous Hyena","Linh cẩu ẩn danh","hyena_lg"],
    ["Anonymous Ibex","Dê Ibex ẩn danh","ibex_lg"],
    ["Anonymous Ifrit","Ifrit ẩn danh","ifrit_lg"],
    ["Anonymous Iguana","Cự đà ẩn danh","iguana_lg"],
    ["Anonymous Jackal","Chó rừng ẩn danh","jackal_lg"],
    ["Anonymous Jackalope","Con Jackalope ẩn danh","jackalope_lg"],
    ["Anonymous Kangaroo","Kangaroo ẩn danh","kangaroo_lg"],
    ["Anonymous Koala","Koala ẩn danh","koala_lg"],
    ["Anonymous Kraken","Bạch tuộc khổng lồ ẩn danh","kraken_lg"],
    ["Anonymous Lemur","Vượn cáo ẩn danh","lemur_lg"],
    ["Anonymous Leopard","Báo hoa mai ẩn danh","leopard_lg"],
    ["Anonymous Liger","Sư hổ ẩn danh","liger_lg"],
    ["Anonymous Llama","Lạc đà không bướu ẩn danh","llama_lg"],
    ["Anonymous Manatee","Lợn biển ẩn danh","manatee_lg"],
    ["Anonymous Mink","Chồn vizon ẩn danh","mink_lg"],
    ["Anonymous Monkey","Khỉ ẩn danh","monkey_lg"],
    ["Anonymous Moose","Nai sừng tấm ẩn danh","moose_lg"],
    ["Anonymous Narwhal","Kỳ lân biển ẩn danh","narwhal_lg"],
    ["Anonymous Nyan Cat","Mèo Nyan ẩn danh","nyancat_lg"],
    ["Anonymous Orangutan","Đười ươi ẩn danh","orangutan_lg"],
    ["Anonymous Otter","Rái cá ẩn danh","otter_lg"],
    ["Anonymous Panda","Gấu trúc ẩn danh","panda_lg"],
    ["Anonymous Penguin","Chim cánh cụt ẩn danh","penguin_lg"],
    ["Anonymous Platypus","Thú mỏ vịt ẩn danh","platypus_lg"],
    ["Anonymous Pumpkin","Bí ngô ẩn danh","pumpkin_lg"],
    ["Anonymous Python","Trăn ẩn danh","python_lg"],
    ["Anonymous Quagga","Lừa vằn ẩn danh","quagga_lg"],
    ["Anonymous Rabbit","Thỏ ẩn danh","rabbit_lg"],
    ["Anonymous Raccoon","Gấu mèo Mỹ ẩn danh","raccoon_lg"],
    ["Anonymous Rhino","Tê giác ẩn danh","rhino_lg"],
    ["Anonymous Sheep","Cừu ẩn danh","sheep_lg"],
    ["Anonymous Shrew","Chuột chù ẩn danh","shrew_lg"],
    ["Anonymous Skunk","Chồn hôi ẩn danh","skunk_lg"],
    ["Anonymous Loris","Cu li ẩn danh","slowloris_lg"],
    ["Anonymous Squirrel","Sóc ẩn danh","squirrel_lg"],
    ["Anonymous Tiger","Hổ ẩn danh","tiger_lg"],
    ["Anonymous Turtle","Rùa ẩn danh","turtle_lg"],
    ["Anonymous Walrus","Hải tượng ẩn danh","walrus_lg"],
    ["Anonymous Wolf","Sói ẩn danh","wolf_lg"],
    ["Anonymous Wolverine","Chồn gulo ẩn danh","wolverine_lg"],
    ["Anonymous Wombat","Wombat ẩn danh","wombat_lg"]
]
